#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']

user_post:
    path: /api/users
    methods: ['POST']
    defaults:
        _controller: App\Controller\UserController::postAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: post_user